version: 2

models:
  # Original marketplace intermediate models
  - name: int_marketplace__searches
    description: "Filtered marketplace searches from the previous month"
    columns:
      - name: customer_id
        description: "Unique identifier for the customer"
      - name: report_date
        description: "Date of the search"
      - name: experian_resultset_id
        description: "Unique identifier for the Experian search result"
      - name: requested_product
        description: "Type of financial product requested"

  - name: int_marketplace__leads_classified
    description: "Filtered and classified leads from the previous month"
    columns:
      - name: customer_id
        description: "Unique identifier for the customer"
      - name: report_date
        description: "Date the lead was created"
      - name: lead_id
        description: "Unique identifier for the lead"
      - name: experian_resultset_id
        description: "Experian search result ID that generated this lead"
      - name: lead_type
        description: "Classification of lead: 0 = zero eligibility lead, 1 = regular lead"
      - name: rpl_id
        description: "Composite ID for joining with RPL forecast data"

  - name: int_marketplace__searches_with_leads
    description: "Searches joined with their corresponding leads"
    columns:
      - name: customer_id
        description: "Unique identifier for the customer"
      - name: report_date
        description: "Date of the search"
      - name: experian_resultset_id
        description: "Unique identifier for the Experian search result"
      - name: requested_product
        description: "Type of financial product requested"
      - name: lead_id
        description: "Unique identifier for the lead (NULL if no lead was generated)"
      - name: lead_type
        description: "Classification of lead: 0 = zero eligibility lead, 1 = regular lead (NULL if no lead)"
      - name: rpl_id
        description: "Composite ID for joining with RPL forecast data (NULL if no lead)"

  - name: int_marketplace__searches_leads_with_revenue
    description: "Searches and leads enriched with revenue data and deduplicated"
    columns:
      - name: customer_id
        description: "Unique identifier for the customer"
      - name: report_date
        description: "Date of the search/lead"
      - name: experian_resultset_id
        description: "Unique identifier for the Experian search result"
      - name: requested_product
        description: "Type of financial product requested"
      - name: lead_id
        description: "Unique identifier for the lead (NULL if no lead was generated)"
      - name: lead_type
        description: "Classification of lead: 0 = zero eligibility lead, 1 = regular lead (NULL if no lead)"
      - name: rpl_id
        description: "Composite ID used for joining with RPL data (NULL if no lead)"
      - name: revenue
        description: "Forecasted revenue for this lead (0 if no lead or no RPL data)"

  # New customer engagement intermediate models
  - name: int_customer__tenure
    description: "Customer tenure and subscription metrics"
    columns:
      - name: customer_id
        description: "Unique identifier for the customer"
        tests:
          - not_null
      - name: first_subscription_date
        description: "Date of the customer's first subscription"
        tests:
          - not_null
      - name: total_days_as_customer
        description: "Total number of days since first subscription"
      - name: total_months_as_customer
        description: "Total number of months since first subscription"
      - name: total_active_days
        description: "Total number of days with active subscriptions"
      - name: total_subscriptions
        description: "Total number of subscriptions the customer has had"
      - name: total_cancellations
        description: "Total number of canceled subscriptions"
      - name: customer_tenure_segment
        description: "Segment based on customer tenure (New, Recent, Engaged, Loyal)"
      - name: current_subscription_id
        description: "ID of current active subscription, if any"
      - name: current_plan_type
        description: "Type of current plan, if any"
      - name: current_plan_tier
        description: "Tier of current plan, if any"
      - name: current_tier_level
        description: "Numerical level of current tier, if any"
      - name: current_monthly_fee
        description: "Monthly fee of current subscription, if any"
      - name: current_days_subscribed
        description: "Days in current subscription, if any"
      - name: active_percentage
        description: "Percentage of total customer days that had active subscriptions"

  - name: int_customer__referral_metrics
    description: "Customer referral activity and performance metrics"
    columns:
      - name: customer_id
        description: "Unique identifier for the customer"
        tests:
          - not_null
      - name: total_referrals_made
        description: "Total number of referrals made by this customer"
      - name: successful_referrals
        description: "Number of referrals that converted successfully"
      - name: total_referral_bonus_earned
        description: "Total bonus amount earned from referrals"
      - name: first_referral_date
        description: "Date of customer's first referral"
      - name: last_referral_date
        description: "Date of customer's most recent referral"
      - name: referrals_last_3_months
        description: "Number of referrals made in the last 3 months"
      - name: is_referred_customer
        description: "Flag indicating if this customer was referred by someone else"
      - name: date_referred
        description: "Date when this customer was referred, if applicable"
      - name: referred_by_customer_id
        description: "ID of the customer who referred this person, if applicable"
      - name: referrer_segment
        description: "Segment based on referral activity (Non-referrer, Referrer, Advocate, Champion)"
      - name: is_active_referrer
        description: "Flag indicating if customer has made referrals in the last 3 months"
      - name: referral_conversion_rate
        description: "Percentage of referrals that successfully converted"

  - name: int_customer__cross_sell_eligibility
    description: "Customer eligibility for cross-sell and upgrade opportunities"
    columns:
      - name: customer_id
        description: "Unique identifier for the customer"
        tests:
          - not_null
      - name: customer_tenure_segment
        description: "Segment based on customer tenure"
      - name: total_months_as_customer
        description: "Total months since first subscription"
      - name: current_plan_type
        description: "Type of current plan, if any"
      - name: current_plan_tier
        description: "Tier of current plan, if any"
      - name: current_tier_level
        description: "Numerical level of current tier, if any"
      - name: active_percentage
        description: "Percentage of total customer days that had active subscriptions"
      - name: total_marketplace_searches
        description: "Total marketplace searches by this customer"
      - name: total_marketplace_leads
        description: "Total marketplace leads generated by this customer"
      - name: total_marketplace_revenue
        description: "Total marketplace revenue generated by this customer"
      - name: has_searched_creditcard
        description: "Flag indicating if customer has searched for credit cards"
      - name: has_searched_loan
        description: "Flag indicating if customer has searched for loans"
      - name: has_searched_car_finance
        description: "Flag indicating if customer has searched for car finance"
      - name: has_searched_car_re_finance
        description: "Flag indicating if customer has searched for car refinance"
      - name: eligible_for_premium_upgrade
        description: "Flag indicating if customer is eligible for premium plan upgrade"
      - name: eligible_for_tier_upgrade
        description: "Flag indicating if customer is eligible for tier upgrade"
      - name: eligible_for_exclusive_offers
        description: "Flag indicating if customer is eligible for exclusive offers"
      - name: eligible_for_premium_creditcard
        description: "Flag indicating if customer is eligible for premium credit card offers"
      - name: eligible_for_preferred_loan_rates
        description: "Flag indicating if customer is eligible for preferred loan rates"
      - name: cross_sell_score
        description: "Overall score for cross-sell potential (0-100)"