version: 2

models:
  - name: int_marketplace__searches
    description: "Filtered marketplace searches from the previous month"
    columns:
      - name: customer_id
        description: "Unique identifier for the customer"
      - name: report_date
        description: "Date of the search"
      - name: experian_resultset_id
        description: "Unique identifier for the Experian search result"
      - name: requested_product
        description: "Type of financial product requested"

  - name: int_marketplace__leads_classified
    description: "Filtered and classified leads from the previous month"
    columns:
      - name: customer_id
        description: "Unique identifier for the customer"
      - name: report_date
        description: "Date the lead was created"
      - name: lead_id
        description: "Unique identifier for the lead"
      - name: experian_resultset_id
        description: "Experian search result ID that generated this lead"
      - name: lead_type
        description: "Classification of lead: 0 = zero eligibility lead, 1 = regular lead"
      - name: rpl_id
        description: "Composite ID for joining with RPL forecast data"

  - name: int_marketplace__searches_with_leads
    description: "Searches joined with their corresponding leads"
    columns:
      - name: customer_id
        description: "Unique identifier for the customer"
      - name: report_date
        description: "Date of the search"
      - name: experian_resultset_id
        description: "Unique identifier for the Experian search result"
      - name: requested_product
        description: "Type of financial product requested"
      - name: lead_id
        description: "Unique identifier for the lead (NULL if no lead was generated)"
      - name: lead_type
        description: "Classification of lead: 0 = zero eligibility lead, 1 = regular lead (NULL if no lead)"
      - name: rpl_id
        description: "Composite ID for joining with RPL forecast data (NULL if no lead)"

  - name: int_marketplace__searches_leads_with_revenue
    description: "Searches and leads enriched with revenue data and deduplicated"
    columns:
      - name: customer_id
        description: "Unique identifier for the customer"
      - name: report_date
        description: "Date of the search/lead"
      - name: experian_resultset_id
        description: "Unique identifier for the Experian search result"
      - name: requested_product
        description: "Type of financial product requested"
      - name: lead_id
        description: "Unique identifier for the lead (NULL if no lead was generated)"
      - name: lead_type
        description: "Classification of lead: 0 = zero eligibility lead, 1 = regular lead (NULL if no lead)"
      - name: rpl_id
        description: "Composite ID used for joining with RPL data (NULL if no lead)"
      - name: revenue
        description: "Forecasted revenue for this lead (0 if no lead or no RPL data)"