
version: 2

models:
  - name: stg_reporting__product_history
    description: "Standardized product history data with clean column naming and proper data types"
    columns:
      - name: customer_id
        description: "Unique identifier for the customer (from APPLICANTID)"
        tests:
          - not_null
      - name: report_date
        description: "Date of the product search"
        tests:
          - not_null
      - name: experian_resultset_id
        description: "Unique identifier for the Experian search result"
        tests:
          - not_null
          - unique
      - name: requested_product
        description: "Type of financial product requested (creditcard, loan, carfinance, or carrefinance)"
        tests:
          - not_null
          - accepted_values:
              values: ['creditcard', 'loan', 'carfinance', 'carrefinance']

  - name: stg_reporting__leads
    description: "Standardized leads data with classification by lead type"
    columns:
      - name: customer_id
        description: "Unique identifier for the customer"
        tests:
          - not_null
      - name: report_date
        description: "Date the lead was created"
        tests:
          - not_null
      - name: lead_id
        description: "Unique identifier for the lead"
        tests:
          - not_null
          - unique
      - name: experian_resultset_id
        description: "Experian search result ID that generated this lead"
        tests:
          - not_null
      - name: lead_type
        description: "Classification of lead: 0 = zero eligibility lead, 1 = regular lead"
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]
      - name: rpl_id
        description: "Composite ID for joining with RPL forecast data"
        tests:
          - not_null
      - name: product_provider
        description: "Company providing the financial product"
      - name: product_id
        description: "Unique identifier for the product"
      - name: product_category
        description: "Category of the product (Card, Loan, Car)"
      - name: product_description
        description: "Detailed description of the product"

  - name: stg_analytics_corvette__marketplace_trading_rpls
    description: "Standardized RPL (Revenue Per Lead) forecast data"
    columns:
      - name: rpl_id
        description: "Composite ID that joins with the leads data"
        tests:
          - not_null
      - name: month
        description: "Month for which the RPL forecast applies"
        tests:
          - not_null
      - name: rpl_forecast
        description: "Forecasted revenue per lead amount"
        tests:
          - not_null

  - name: stg_events
    description: Standardized events data with basic transformations
    columns:
      - name: event_guid
        description: Unique identifier for each event
        tests:
          - not_null
          - unique
      - name: customer_id
        description: Unique identifier for the customer
      - name: event_type
        description: Type of event
      - name: event_category
        description: Category of the event
      - name: event_datetime
        description: Date and time when the event occurred
      - name: platform
        description: Platform on which the event occurred
      - name: revenue
        description: Revenue associated with the event (if applicable)
        tests:
          - not_null:
              where: "event_category IN ('MP Lead', 'upsell', 'payment_success')"

  - name: stg_customers
    description: Standardized customer data with basic transformations
    columns:
      - name: customer_id
        description: Unique identifier for the customer
        tests:
          - not_null
          - unique
      - name: customer_age
        description: Age of the customer
      - name: customer_age_band
        description: Age band of the customer
      - name: customer_is_prospect
        description: Indicates if the customer is a prospect
        tests:
          - accepted_values:
              values: [TRUE, FALSE]
      - name: effective_date
        description: Date the customer record became effective
      - name: is_current
        description: Indicates if the customer record is current
        tests:
          - accepted_values:
              values: [TRUE, FALSE]

  - name: stg_products
    description: Standardized product data with basic transformations
    columns:
      - name: product_id
        description: Unique identifier for the product
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('seed_product_mapping')
              field: product_id
      - name: product_name
        description: Name of the product
      - name: product_family
        description: Family group of the product
      - name: product_type
        description: Type of product
      - name: price
        description: Product price
        tests:
          - not_null
      - name: is_active
        description: Indicates if the product is active

  - name: stg_subscriptions
    description: Standardized subscription data with basic transformations
    columns:
      - name: subscription_id
        description: Unique identifier for the subscription
        tests:
          - not_null
          - unique
      - name: customer_id
        description: Unique identifier for the customer
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: product_id
        description: Unique identifier for the product
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id
      - name: start_date
        description: Start date of the subscription
        tests:
          - not_null
      - name: end_date
        description: End date of the subscription (if applicable)
      - name: status
        description: Status of the subscription
        tests:
          - accepted_values:
              values: ['active', 'cancelled', 'expired', 'pending']
      - name: payment_method
        description: Payment method for the subscription
      - name: billing_frequency
        description: Billing frequency
      - name: monthly_amount
        description: Monthly subscription amount
        tests:
          - not_null          